# Use custom format
format = '''
$os$time$directory$git_branch'''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[git_branch]
format='[$branch(:$remote_branch) ]($style)'
style = 'bold red'

[os]
disabled = false
style='grey'

[os.symbols]
Debian = " "
FreeBSD = " "
Linux = " "
Macos = " "
Ubuntu = " "
Unknown = " "
Windows = " "


[time]
disabled = false
format = '[$time]($style) '
style='grey'
